# Generated by Django 3.2.14 on 2022-07-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='memo',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='todomodel',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
